### ISSUE TITLE
Delay doesn't work both ways

### ISSUE THREAD

**Issue by musafarouk** [QingWei-Li/vue-delay#1]
Delay doesn't work when going back to previously visited pages.

**Comment by QingWei-Li** [comment]
Any example?

**Comment by musafarouk** [comment]
This is the link to the finished work. Try visiting the pages twice. https://www.elitecourierdelivery.info/

**Comment by QingWei-Li** [comment]
I don't understand where the delay component is used, and how do I trigger the bug?

**Comment by musafarouk** [comment]
I put these in the views i want the delay to work

```html
<template>
<delay :wait="5000">
  <div slot="loading">
    <br><br><br><br>
    <div class="loading-spinner">
      <center>
      <swapping-squares-spinner
  :animation-duration="1000"
  :size="65"
  color="#34A853"
/>
</center>
      </div>
  </div>
  </delay>

<script>
import { SwappingSquaresSpinner } from "epic-spinners";
import Delay from "vue-delay";

export default {
    name: "home",
    components: {
      Card,
      Delay,
      SwappingSquaresSpinner
    },
}
</script>
```

**Comment by QingWei-Li** [comment]
I don't see any errors. 
Maybe you should provide a working example that can trigger a bug so I can find the problem.

**Comment by musafarouk** [comment]
Check the link I sent. Notice how the animation and delay doesn't show when trying to visit the pages again

**Comment by ZhihaoLau** [comment]
#3
